### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by juanpabloe** [CodeandoMexico/congreso-abierto#2]
El landing incluirá una imagen de background estilo: http://startbootstrap.com/templates/grayscale/

Imagen sugerida: http://www.legisladores.org.mx/wp-content/uploads/2013/09/dip.jpg
- [x] h1 que dice: "Congreso Abierto MX"
- [x] La frase del landing algo como: "El ciudadano mexicano vota y luego olvida. ¿Qué pasa en el congreso mientras nadie está poniendo atención?"
- [x] Botón "Entrar".
- [x] Imagen de background

**Comment by lalo** [comment]
Sólo falta otra tipografia pero no se que sugieran sobre eso y ya lo ponemos en otro pull request.

**Comment by juanpabloe** [comment]
Great
