### ISSUE TITLE
links en footer

### ISSUE THREAD

**Issue by juanpabloe** [CodeandoMexico/congreso-abierto#7]
agregar links al footer:
- [x] GitHub: https://github.com/CodeandoMexico/congreso-abierto
- [ ] Datasets: link a datamx.io con los datasets
- [x] Twitter: https://twitter.com/CodeandoMexico
- [x] Contacto: mailto:equipo@codeandomexico.org

**Comment by lalo** [comment]
quien me ayuda con esto?
