### ISSUE TITLE
colores más suaves en gráficas

### ISSUE THREAD

**Issue by juanpabloe** [CodeandoMexico/congreso-abierto#8]
ahorita están muy chillantes, en especial el rojo, azul y amarillo:

![screen shot 2014-06-02 at 7 07 05 pm](https://cloud.githubusercontent.com/assets/542209/3154861/21a6e56a-eab3-11e3-8ede-058c13209f0b.png)

Sería bueno colores más suaves que no maten la sensación de seguir leyendo

**Comment by lalo** [comment]
Ya quedo, esta en el branch develop
